Update tvp.yml

diff --git a/.github/workflows/tvp.yml b/.github/workflows/tvp.yml
--- a/.github/workflows/tvp.yml
+++ b/.github/workflows/tvp.yml
@@ -27,9 +27,9 @@ jobs:
 
       - name: fetch content tvp
         run: |
-          python3 ressources/wld/tvpin.py > ressources/wld/tvpin.m3u8
-          python3 ressources/wld/tvpol.py > ressources/wld/tvpol.m3u8
-          python3 ressources/wld/tvpwd.py > ressources/wld/tvpwd.m3u8
+          python3 ressources/wld/tvpin.py > ressources/wld/tvpin.m3u8 || echo "tvpin failed"
+          python3 ressources/wld/tvpol.py > ressources/wld/tvpol.m3u8 || echo "tvpol failed"
+          python3 ressources/wld/tvpwd.py > ressources/wld/tvpwd.m3u8 || echo "tvpwd failed"
 
       - name: git add
         run: |
